### ISSUE TITLE
No link from Rathenauplatz to Maxfeld?

### ISSUE THREAD

**Issue by gwselke** [stelim/Map-Tube-Nuremberg#7]
It seems the data specify a (undirectional) link from Maxfeld (id 0331) to Rathenauplatz (id 0332) (using U3), but not the other way round. This looks like a (minor) oversight.

**Comment by stelim** [comment]
Thank you for your issue. I indeed missed the connection.

**Comment by gwselke** [comment]
Thank you for the fast fix, Stefan!
